import { notFound } from "next/navigation";
import { TopNav } from "@/components/layout/TopNav";
import { Footer } from "@/components/layout/Footer";
import { StatusChip } from "@/components/ui/StatusChip";
import { formatBps, shortHash } from "@/lib/format";
import type { TruthRecord } from "@/lib/api";

const API_BASE_URL = process.env.NEXT_PUBLIC_API_BASE_URL ?? "http://localhost:8080";

async function getTruthRecord(id: string) {
  try {
    const res = await fetch(`${API_BASE_URL}/truth-records/${id}`, { cache: "no-store" });
    if (res.status === 404) return null;
    if (!res.ok) return "unreachable" as const;
    const data = await res.json();
    return data.truthRecord as TruthRecord;
  } catch {
    return "unreachable" as const;
  }
}

export default async function TruthRecordPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const record = await getTruthRecord(id);

  if (record === null) notFound();

  return (
    <>
      <TopNav />
      <main className="flex-1 w-full max-w-[1280px] mx-auto p-4 md:p-12">
        {record === "unreachable" ? (
          <div className="bg-error-container/20 border border-error/30 text-error rounded-lg p-4 text-sm">
            Couldn&apos;t reach the WitnessWeave API to load this Truth Record.
          </div>
        ) : (
          <TruthRecordView record={record} />
        )}
      </main>
      <Footer />
    </>
  );
}

function TruthRecordView({ record }: { record: TruthRecord }) {
  const isPassed = record.verdict === "passed";

  return (
    <>
      <div className="mb-12 flex flex-col md:flex-row justify-between items-start md:items-end gap-6 border-b border-border-subtle pb-6">
        <div>
          <div className="flex items-center gap-3 mb-2">
            <StatusChip status={record.verdict} />
            <span className="font-mono text-xs text-text-secondary">EVAL-{shortHash(record.bounty_id, 6)}</span>
          </div>
          <h1 className="text-3xl md:text-4xl font-semibold text-text-primary mb-2">
            Immutable Truth Record <span className="text-secondary/70">#{shortHash(record.id, 4)}</span>
          </h1>
          <p className="text-text-secondary max-w-2xl">
            Final consensus output generated by the GenLayer verifiable evaluation network. This record is
            cryptographically sealed and immutable — it reflects a credible consensus, not a claim of
            objective truth.
          </p>
        </div>
        <div className="holographic-seal px-6 py-4 rounded flex flex-col items-center justify-center border border-secondary/30 bg-secondary/5 shrink-0">
          <span className="text-secondary text-2xl mb-1">✓</span>
          <span className="font-mono text-[10px] text-secondary tracking-widest uppercase">
            {isPassed ? "Verified Seal" : "Recorded Outcome"}
          </span>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-12 gap-6">
        <section className="col-span-1 md:col-span-8 flex flex-col gap-6">
          <div className="bg-surface-elevated border border-border-subtle rounded-lg p-6 truth-border-active">
            <h2 className="text-lg font-medium text-text-primary mb-4">The Consensus</h2>
            <div className="bg-surface-base border border-border-subtle rounded p-5">
              <p className="text-text-primary leading-relaxed mb-4">{record.description}</p>
              <p className="text-on-surface-variant leading-relaxed">{record.rationale}</p>

              {record.final_state_root && (
                <div className="mt-6 bg-background-deep border border-outline-variant/30 rounded p-4">
                  <div className="flex justify-between items-center mb-2">
                    <span className="font-mono text-[10px] text-text-secondary">FINAL_STATE_ROOT</span>
                  </div>
                  <code className="font-mono text-[11px] text-on-surface-variant break-all">
                    {record.final_state_root}
                  </code>
                </div>
              )}
            </div>
          </div>
        </section>

        <section className="col-span-1 md:col-span-4 flex flex-col gap-6">
          <div className="bg-surface-elevated border border-border-subtle rounded-lg p-6 flex flex-col items-center justify-center min-h-[200px]">
            <span className="font-mono text-[10px] text-text-secondary uppercase tracking-widest mb-4">
              Confidence Score
            </span>
            <div className="flex flex-col items-center justify-center">
              <span className="text-4xl font-bold text-text-primary leading-none">
                {formatBps(record.confidence_bps)}
              </span>
              <span className="font-mono text-[10px] text-secondary mt-2 uppercase">
                {record.confidence_bps >= 7000 ? "High" : record.confidence_bps >= 4000 ? "Moderate" : "Low"}
              </span>
            </div>
          </div>

          <div className="bg-surface-elevated border border-border-subtle rounded-lg p-6 flex flex-col">
            <h2 className="text-lg font-medium text-text-primary mb-6 border-b border-border-subtle pb-4">
              Provenance
            </h2>
            <div className="flex flex-col gap-5">
              <ProvenanceField label="GenLayer Contract">{shortHash(record.contract_address)}</ProvenanceField>
              {record.settle_tx_hash && (
                <ProvenanceField label="Settlement Transaction">{shortHash(record.settle_tx_hash)}</ProvenanceField>
              )}
              <ProvenanceField label="Published">
                {new Date(record.published_at).toLocaleString(undefined, { dateStyle: "medium", timeStyle: "short" })}
              </ProvenanceField>
              {record.payout_bps !== null && (
                <ProvenanceField label="Payout Split">{formatBps(record.payout_bps)} to builder</ProvenanceField>
              )}
            </div>
          </div>
        </section>
      </div>
    </>
  );
}

function ProvenanceField({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <div className="flex flex-col">
      <span className="font-mono text-[10px] text-text-secondary uppercase tracking-wider mb-1">{label}</span>
      <div className="flex items-center justify-between bg-surface-base border border-border-subtle rounded p-2">
        <code className="font-mono text-xs text-primary">{children}</code>
      </div>
    </div>
  );
}
